server:
  port: 86379

spring:
  application:
    name: cloud-redis-service


redis:
  # master连接密码
  password: myredis
  # 集群
  cluster:
    # 集群节点
    nodes: 192.168.211.158:6382,192.168.211.158:6383,192.168.211.158:6384,192.168.211.158:6385,192.168.211.158:6386,192.168.211.158:6387
    # redis读写超时时间（毫秒）
    socketTimeout: 1000
    # redis连接超时时间（毫秒）
    connectionTimeOut: 3000
    # 最大尝试连接次数
    maxAttempts: 10
    # 最大重定向次数
    maxRedirects: 5
  # 连接池
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    maxActive: 150
    # 连接池中的最大空闲连接
    maxIdle: 10
    # 连接池中的最小空闲连接
    minIdle: 1
    # 获取连接时的最大等待毫秒数,小于零:阻塞不确定的时间,默认-1
    maxWaitMillis: 3000
    # 每次释放连接的最大数目
    numTestsPerEvictionRun: 50
    # 释放连接的扫描间隔（毫秒）
    timeBetweenEvictionRunsMillis: 3000
    # 连接最小空闲时间（毫秒）
    minEvictableIdleTimeMillis: 1800000
    # 连接空闲多久后释放, 当空闲时间>该值 且 空闲连接>最大空闲连接数 时直接释放（毫秒）
    softMinEvictableIdleTimeMillis: 10000
    # 在获取连接的时候检查有效性, 默认false
    testOnBorrow: true
    # 在空闲时检查有效性, 默认false
    testWhileIdle: true
    # 在归还给pool时，是否提前进行validate操作
    testOnReturn: true
    # 连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
    blockWhenExhausted: true