server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，通过微服务名进行路由
      routes:
      #路由的ID，没有固定的配置规则，但要求唯一，建议配合服务名配置
      - id: payment_route1
        #uri: http://localhost:8001  #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service #匹配后提供服务的路由地址
        predicates:
        #断言，路径相匹配的进行路由
        - Path=/payment/get/**

      - id: payment_route2
        #uri: http://baidu.com
        uri: lb://cloud-payment-service #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/lb/**
        #- Path=/payment/{childuri}/**   #与AddRequestHeader搭配使用
        #- Before=2021-09-29T11:42:42.915+08:00[Asia/Shanghai]
        #- Cookie=username,test
        #- Header=token,123
        #- Host=**.gateway.com,**.springcloudgateway.com
        #- Method=GET
        #- Query=userId,123
        #- RemoteAddr=192.168.0.1/24

#      # 路由权重
#      - id: payment_weight_high
#        uri: http://localhost:8001
#        predicates:
#        - Path=/payment/lb/**
#        - Weight=group1, 8
#
#      - id: payment_weight_low
#        uri: http://localhost:8002
#        predicates:
#        - Path=/payment/lb/**
#        - Weight=group1, 2

        filters:
        #- AddRequestHeader=X-Request-red,blue
        #- AddRequestHeader=X-Request-red,{childuri}




eureka:
  client:
    #表示收将自己注册到EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service9527
    prefer-ip-address: true   #访问路径可以显示IP地址
