server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://2d77196l54.51vip.biz:24951/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
          url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
          username: root
          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://14.18.67.91:3307/card-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: root
#          password: r421rwfGx.

        flowable:
          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://2d77196l54.51vip.biz:24951/flowable?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
          url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
          username: root
          password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities #所有entity别名所在的包


flowable:
  #当监测到数据库表版本不一致是，会自动升级,没有对应的表会自动创建
  database-schema-update: true
  #关闭定时任务
  async-executor-activate: false
  process-file:
    work-order:
      path: C:\Users\lihw\Desktop\MyHolidayUI.bpmn20.xml
      process-name: 请假流程

