server:
  port: 80

spring:
  application:
    name: nacos-discovery-consumer-order
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 192.168.253.130:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"